workflows:
  umar-horary-android:
    name: Umar Horary Build
    working_directory: .
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - CD android && ./gradlew assemblyRelease                 
    artifacts:                           
      - build/app/outputs/flutter-apk/*.apk